"""empty message

Revision ID: 09864d512214
Revises: ec9b877319bc
Create Date: 2022-12-05 18:49:34.562159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09864d512214'
down_revision = 'ec9b877319bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_message_read_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_message_read_time')

    # ### end Alembic commands ###
