"""empty message

Revision ID: 732819b3170e
Revises: 
Create Date: 2022-12-04 15:22:10.177930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732819b3170e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
