"""empty message

Revision ID: 7fa0653a465a
Revises: 09864d512214
Create Date: 2022-12-05 20:43:25.079295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fa0653a465a'
down_revision = '09864d512214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_new_private_messages', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('num_new_private_messages')

    # ### end Alembic commands ###
